### PR TITLE
console changes for remote relationships

### PR DESCRIPTION
**Pull request by wawhal**
Review app: https://hge-ci-pull-2240.herokuapp.com/console

### CODE REVIEW

**Comment by wawhal** [comment]
@rikinsk please add the code review here.

**Comment by rikinsk** [comment]
@tirumaraiselvan the remote join isn't working with static value. 

see: https://hge-ci-pull-2395.herokuapp.com/console/data/schema/public/tables/user/relationships
and try query: 
{
  user {
    name
    country
    country_info {
      name
      code
    }
  }
}

**Comment by tirumaraiselvan** [comment]
Right. Apparently, empty `[ ]` for hasura join columns is buggy.

**Comment by tirumaraiselvan** [comment]
Let's keep this open for review. But lets not merge it. #2395 is the main PR now.

**Pull request merged**
